import * as Phaser from 'phaser';
import { registerLucideIconTextures } from '../utils/icons.js';

export class BootScene extends Phaser.Scene {
    constructor() {
        super({ key: 'BootScene' });
    }

    preload() {
        // Get loading bar element
        const loadingBar = document.getElementById('loading-bar');

        // Update loading bar as assets load
        this.load.on('progress', (value) => {
            if (loadingBar) {
                loadingBar.style.width = `${value * 100}%`;
            }
        });

        this.load.on('complete', () => {
            // Hide loading screen with fade
            const loadingScreen = document.getElementById('loading-screen');
            if (loadingScreen) {
                loadingScreen.classList.add('hidden');
                setTimeout(() => {
                    loadingScreen.style.display = 'none';
                }, 500);
            }
        });

        // Load Ridgways Rail sprite sheet (4x2 grid, 4000x2233 -> 1000x1116 per frame)
        this.load.spritesheet('rail_sheet', 'assets/sprites/rail_sprite_sheet.png', { frameWidth: 1000, frameHeight: 1116 });

        // Load Harrier sheet (raw image; sliced into flight frames in create())
        this.load.image('harrier_sheet_raw', 'assets/sprites/northern_harrier_sprite.png');

        // Load Cat sprite sheet (7x2 grid, 3500x1014 -> 500x507 per frame)
        this.load.spritesheet('cat_sheet', 'assets/sprites/cat_with_padding.png', {
            frameWidth: 500,
            frameHeight: 507
        });

        // The authored fox sheet includes two labelled animation sequences.
        // Load it raw so create() can crop only the artwork from each pose.
        this.load.image('fox_sheet_raw', 'assets/sprites/gray_fox_sprite.png');

        // Load plant growth sheets (4x2 grid of stages, sprout → mature)
        ['gumplant', 'saltgrass', 'pickleweed', 'cordgrass', 'jaumea'].forEach((key) => {
            this.load.image(`${key}_sheet`, `assets/sprites/${key}_sprite_sheet.png`);
        });
        // Legacy 'plant' key aliases the mature gumplant (set up in slicePlantSheets)

        // Load Intro Video
        this.load.video('intro_video', 'assets/title_movie.mp4');

        this.load.audio('rail_call', 'assets/sprites/ridgways_rail_call.mp3');

        // Create placeholder graphics for other assets
        this.createPlaceholderAssets();
    }

    createPlaceholderAssets() {

        // ── PLANT GROWTH STAGES (sliced from sprite sheets in create()) ──
        // Saltgrass / pickleweed / cordgrass / jaumea / gumplant textures
        // (`{key}_1..{key}_8` + `{key}` aliases) are generated by
        // slicePlantSheets() once the sheet images have loaded.

        // Water tile (64x64) – deep tidal water with depth banding & seamless waves
        const waterGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        // Deep base
        waterGraphics.fillStyle(0x0a3149);
        waterGraphics.fillRect(0, 0, 64, 64);
        // Depth banding
        waterGraphics.fillStyle(0x0d425f, 0.6);
        waterGraphics.fillRect(0, 22, 64, 42);
        // Wave crests – integer sine cycles so the tile repeats seamlessly
        for (let row = 0; row < 4; row++) {
            const yBase = 6 + row * 16;
            waterGraphics.lineStyle(2, 0x2f86ad, 0.32);
            waterGraphics.beginPath();
            waterGraphics.moveTo(0, yBase + Math.sin(row * 1.7) * 2.2);
            for (let x = 0; x <= 64; x += 4) {
                const t = (x / 64) * Math.PI * 2;
                waterGraphics.lineTo(x, yBase + Math.sin(t * 2 + row * 1.7) * 2.2);
            }
            waterGraphics.strokePath();
        }
        // Secondary ripple lines
        waterGraphics.lineStyle(1, 0x7fd4e8, 0.22);
        for (let row = 0; row < 3; row++) {
            const yBase = 13 + row * 21;
            waterGraphics.beginPath();
            waterGraphics.moveTo(0, yBase + Math.cos(row * 2.3) * 1.6);
            for (let x = 0; x <= 64; x += 4) {
                const t = (x / 64) * Math.PI * 2;
                waterGraphics.lineTo(x, yBase + Math.cos(t * 3 + row * 2.3) * 1.6);
            }
            waterGraphics.strokePath();
        }
        // Subtle foam dots
        waterGraphics.fillStyle(0xffffff, 0.10);
        [
            [8, 6], [30, 18], [52, 10], [14, 42], [44, 50], [58, 34], [22, 58],
        ].forEach(([px, py]) => waterGraphics.fillCircle(px, py, 1.5));
        waterGraphics.generateTexture('water', 64, 64);
        waterGraphics.destroy();

        // Vertical depth shade for the water body (real canvas gradient)
        if (this.textures.exists('water_shade')) this.textures.remove('water_shade');
        const shadeTex = this.textures.createCanvas('water_shade', 4, 64);
        const shadeCtx = shadeTex.getContext();
        const shadeGrad = shadeCtx.createLinearGradient(0, 0, 0, 64);
        shadeGrad.addColorStop(0, 'rgba(5,26,40,0)');
        shadeGrad.addColorStop(0.6, 'rgba(5,26,40,0.18)');
        shadeGrad.addColorStop(1, 'rgba(5,26,40,0.5)');
        shadeCtx.fillStyle = shadeGrad;
        shadeCtx.fillRect(0, 0, 4, 64);
        shadeTex.refresh();

        // Soft contact shadow (radial gradient squashed into an ellipse)
        if (this.textures.exists('shadow')) this.textures.remove('shadow');
        const shadowTex = this.textures.createCanvas('shadow', 128, 40);
        const shadowCtx = shadowTex.getContext();
        shadowCtx.translate(64, 20);
        shadowCtx.scale(1, 0.32);
        shadowCtx.translate(-64, -20);
        const shadowGrad = shadowCtx.createRadialGradient(64, 20, 2, 64, 20, 60);
        shadowGrad.addColorStop(0, 'rgba(0,0,0,0.42)');
        shadowGrad.addColorStop(0.7, 'rgba(0,0,0,0.20)');
        shadowGrad.addColorStop(1, 'rgba(0,0,0,0)');
        shadowCtx.fillStyle = shadowGrad;
        shadowCtx.fillRect(-10, -60, 148, 160);
        shadowTex.refresh();

        // Water-edge / shoreline overlay (16x64) for foam & wet-sand at the tide front
        const edgeGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        // Wet sand strip
        edgeGraphics.fillGradientStyle(0x3a6e9f, 0x3a6e9f, 0x5d4e37, 0x5d4e37);
        edgeGraphics.fillRect(0, 0, 16, 64);
        // Foam line
        edgeGraphics.fillStyle(0xffffff, 0.55);
        edgeGraphics.fillRect(0, 0, 4, 64);
        edgeGraphics.fillStyle(0xffffff, 0.3);
        edgeGraphics.fillRect(4, 0, 3, 64);
        // Scattered foam blobs
        edgeGraphics.fillStyle(0xffffff, 0.25);
        [6, 18, 30, 44, 56].forEach(py => {
            edgeGraphics.fillCircle(3, py, 2);
            edgeGraphics.fillCircle(7, py + 8, 1.5);
        });
        edgeGraphics.generateTexture('water_edge', 16, 64);
        edgeGraphics.destroy();

        // Mud/transition zone tile (64x64)
        const mudGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        mudGraphics.fillStyle(0x5d4e37);
        mudGraphics.fillRect(0, 0, 64, 64);
        // Texture details
        mudGraphics.fillStyle(0x4a3f2d, 0.5);
        mudGraphics.fillCircle(10, 15, 5);
        mudGraphics.fillCircle(45, 30, 7);
        mudGraphics.fillCircle(25, 50, 4);
        mudGraphics.fillCircle(55, 10, 3);
        mudGraphics.generateTexture('mud', 64, 64);
        mudGraphics.destroy();

        // Upland/grass tile (64x64)
        const grassGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        grassGraphics.fillStyle(0x4a7c23);
        grassGraphics.fillRect(0, 0, 64, 64);
        // Grass blades
        grassGraphics.fillStyle(0x5a8c33);
        for (let i = 0; i < 20; i++) {
            const x = Math.random() * 64;
            const y = Math.random() * 64;
            grassGraphics.fillTriangle(x, y + 8, x + 3, y, x + 6, y + 8);
        }
        grassGraphics.generateTexture('grass', 64, 64);
        grassGraphics.destroy();

        // Seed particle (16x16)
        const seedGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        seedGraphics.fillStyle(0xf39c12);
        seedGraphics.fillCircle(8, 8, 4);
        seedGraphics.fillStyle(0xffffff, 0.5);
        seedGraphics.lineStyle(1, 0xffffff, 0.7);
        seedGraphics.beginPath();
        seedGraphics.moveTo(8, 4);
        seedGraphics.lineTo(8, 0);
        seedGraphics.lineTo(12, 2);
        seedGraphics.stroke();
        seedGraphics.generateTexture('seed', 16, 16);
        seedGraphics.destroy();

        // Heart particle (16x16)
        const heartGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        heartGraphics.fillStyle(0xff6b9d);
        heartGraphics.fillCircle(5, 6, 4);
        heartGraphics.fillCircle(11, 6, 4);
        heartGraphics.fillTriangle(1, 8, 8, 15, 15, 8);
        heartGraphics.generateTexture('heart', 16, 16);
        heartGraphics.destroy();

        // Dirt particle (8x8)
        const dirtGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        dirtGraphics.fillStyle(0x8b7355);
        dirtGraphics.fillCircle(4, 4, 3);
        dirtGraphics.generateTexture('dirt', 8, 8);
        dirtGraphics.destroy();

        // Button texture (200x60)
        const buttonGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        buttonGraphics.fillStyle(0x27ae60);
        buttonGraphics.fillRoundedRect(0, 0, 200, 60, 12);
        buttonGraphics.lineStyle(3, 0x2ecc71);
        buttonGraphics.strokeRoundedRect(0, 0, 200, 60, 12);
        buttonGraphics.generateTexture('button', 200, 60);
        buttonGraphics.destroy();

        // Button hover texture
        const buttonHoverGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        buttonHoverGraphics.fillStyle(0x2ecc71);
        buttonHoverGraphics.fillRoundedRect(0, 0, 200, 60, 12);
        buttonHoverGraphics.lineStyle(3, 0x58d68d);
        buttonHoverGraphics.strokeRoundedRect(0, 0, 200, 60, 12);
        buttonHoverGraphics.generateTexture('button_hover', 200, 60);
        buttonHoverGraphics.destroy();

        // ── HUD panel texture (reused for all panels) ──
        const hPnl = this.make.graphics({ x: 0, y: 0, add: false });
        hPnl.fillStyle(0x0a160e, 0.88);
        hPnl.fillRoundedRect(0, 0, 220, 52, 12);
        hPnl.lineStyle(1.5, 0x3ddc84, 0.45);
        hPnl.strokeRoundedRect(0, 0, 220, 52, 12);
        hPnl.lineStyle(1, 0xffffff, 0.12);
        hPnl.strokeRoundedRect(2, 2, 216, 48, 10);
        hPnl.generateTexture('hud_panel', 220, 52);
        hPnl.destroy();

        const hPnlW = this.make.graphics({ x: 0, y: 0, add: false });
        hPnlW.fillStyle(0x0a160e, 0.88);
        hPnlW.fillRoundedRect(0, 0, 260, 52, 12);
        hPnlW.lineStyle(1.5, 0xf39c12, 0.45);
        hPnlW.strokeRoundedRect(0, 0, 260, 52, 12);
        hPnlW.lineStyle(1, 0xffffff, 0.12);
        hPnlW.strokeRoundedRect(2, 2, 256, 48, 10);
        hPnlW.generateTexture('hud_panel_wide', 260, 52);
        hPnlW.destroy();

        const hPnlF = this.make.graphics({ x: 0, y: 0, add: false });
        hPnlF.fillStyle(0x08140c, 0.88);
        hPnlF.fillRoundedRect(0, 0, 240, 44, 22);
        hPnlF.lineStyle(1.5, 0x3ddc84, 0.4);
        hPnlF.strokeRoundedRect(0, 0, 240, 44, 22);
        hPnlF.generateTexture('hud_flock_panel', 240, 44);
        hPnlF.destroy();

        const hPnlFooter = this.make.graphics({ x: 0, y: 0, add: false });
        hPnlFooter.fillStyle(0x07120a, 0.92);
        hPnlFooter.fillRect(0, 0, 960, 44);
        hPnlFooter.lineStyle(1.5, 0x3ddc84, 0.45);
        hPnlFooter.beginPath();
        hPnlFooter.moveTo(0, 1);
        hPnlFooter.lineTo(960, 1);
        hPnlFooter.strokePath();
        hPnlFooter.lineStyle(1, 0xffffff, 0.1);
        hPnlFooter.beginPath();
        hPnlFooter.moveTo(0, 3);
        hPnlFooter.lineTo(960, 3);
        hPnlFooter.strokePath();
        hPnlFooter.generateTexture('hud_footer_bar', 960, 44);
        hPnlFooter.destroy();

        const hPnlB = this.make.graphics({ x: 0, y: 0, add: false });
        hPnlB.fillStyle(0x0c1a0c, 0.72);
        hPnlB.fillRoundedRect(0, 0, 480, 36, 8);
        hPnlB.lineStyle(1, 0xffffff, 0.15);
        hPnlB.strokeRoundedRect(0, 0, 480, 36, 8);
        hPnlB.generateTexture('hud_panel_bottom', 480, 36);
        hPnlB.destroy();

        // Legacy textures kept for menu / game-over scenes
        const seedBankGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        seedBankGraphics.fillStyle(0x000000, 0.4);
        seedBankGraphics.fillRoundedRect(0, 0, 280, 80, 16);
        seedBankGraphics.lineStyle(2, 0xffffff, 0.2);
        seedBankGraphics.strokeRoundedRect(0, 0, 280, 80, 16);
        seedBankGraphics.generateTexture('seedbank_bg', 280, 80);
        seedBankGraphics.destroy();

        const scorePanelGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        scorePanelGraphics.fillStyle(0x000000, 0.4);
        scorePanelGraphics.fillRoundedRect(0, 0, 200, 120, 16);
        scorePanelGraphics.lineStyle(2, 0xffffff, 0.2);
        scorePanelGraphics.strokeRoundedRect(0, 0, 200, 120, 16);
        scorePanelGraphics.generateTexture('score_panel', 200, 120);
        scorePanelGraphics.destroy();

        registerLucideIconTextures(this);

        this.applyNearestFilter();
    }

    applyNearestFilter() {
        const spriteKeys = [
            'cat',
            'cat_walking_1', 'cat_walking_2', 'cat_walking_3', 'cat_walking_4',
            'cat_pouncing', 'cat_with_kill',
            'water', 'water_edge', 'mud', 'grass',
            'seed', 'heart', 'dirt',
            'button', 'button_hover',
            'seedbank_bg', 'score_panel',
            'hud_panel', 'hud_panel_wide', 'hud_panel_bottom',
            'rail_running_1', 'rail_running_2', 'rail_running_3', 'rail_running_4',
            'rail_sprint_1', 'rail_sprint_2', 'rail_sprint_3', 'rail_sprint_4',
            'rail_hiding', 'rail_calling', 'rail_surprised',
            'fox_run_1', 'fox_run_2', 'fox_run_3', 'fox_run_4',
            'fox_run_5', 'fox_run_6', 'fox_run_7',
            'fox_pounce_1', 'fox_pounce_2', 'fox_pounce_3', 'fox_pounce_4',
            'fox_pounce_5', 'fox_pounce_6', 'fox_pounce_7', 'fox_pounce_8',
            'cat_sheet',
        ];
        spriteKeys.forEach(key => {
            const tex = this.textures.get(key);
            if (tex && tex.source && tex.source[0]) {
                tex.setFilter(Phaser.Textures.FilterMode.NEAREST);
            }
        });
    }

    create() {
        // Split the rail sheet into named textures (Rail.js references these keys)
        this.sliceRailSheet();

        // Split plant growth sheets into staged textures (Plant.js uses these)
        this.slicePlantSheets();

        // Split the harrier sheet into flight frames (Harrier.js uses these)
        this.sliceHarrier();

        // Split the labelled fox reference sheet into clean gameplay frames
        this.sliceFoxSheet();

        // Re-apply NEAREST now that the sliced rail textures exist
        // (plant stage textures intentionally keep LINEAR filtering)
        this.applyNearestFilter();

        // Transition to menu scene
        this.scene.start('MenuScene');
    }

    // ─── GRAY FOX SHEET SLICER ─────────────────────────────────

    /** The 4784x3584 source is an authored 4x4 reference sheet rather than a
     *  tightly packed atlas: rows 1-2 contain seven running poses (cell 8 is
     *  intentionally empty), and rows 3-4 contain eight pounce/carry poses.
     *  The explicit artwork bounds avoid headings, frame labels, and poses
     *  that extend across nominal cell edges. Every pose is then placed on a
     *  shared 450x250 bottom-centred canvas to keep the fox grounded and the
     *  existing world scale stable throughout both sequences. */
    sliceFoxSheet() {
        if (!this.textures.exists('fox_sheet_raw')) return;

        const CANVAS_W = 450;
        const CANVAS_H = 250;
        const SOURCE_SCALE = 0.32;
        const GROUND_Y = 242;
        const src = this.textures.get('fox_sheet_raw').source[0].image;
        const frames = [
            ['fox_run_1', 270, 404, 825, 428],
            ['fox_run_2', 1200, 399, 1031, 433],
            ['fox_run_3', 2374, 409, 1070, 452],
            ['fox_run_4', 3589, 383, 1051, 475],
            ['fox_run_5', 147, 1082, 1060, 451],
            ['fox_run_6', 1312, 1081, 1027, 442],
            ['fox_run_7', 2435, 1072, 1033, 438],
            ['fox_pounce_1', 106, 2161, 963, 382],
            ['fox_pounce_2', 1172, 2123, 973, 447],
            ['fox_pounce_3', 2264, 2123, 1364, 457],
            ['fox_pounce_4', 3702, 2148, 1027, 456],
            ['fox_pounce_5', 112, 2835, 1066, 561],
            ['fox_pounce_6', 1267, 2850, 1055, 562],
            ['fox_pounce_7', 2507, 2833, 1089, 564],
            ['fox_pounce_8', 3666, 2861, 1070, 552],
        ];

        frames.forEach(([key, sx, sy, sw, sh]) => {
            if (this.textures.exists(key)) this.textures.remove(key);
            const texture = this.textures.createCanvas(key, CANVAS_W, CANVAS_H);
            if (!texture) return;

            const ctx = texture.getContext();
            ctx.imageSmoothingEnabled = false;
            const dw = Math.round(sw * SOURCE_SCALE);
            const dh = Math.round(sh * SOURCE_SCALE);
            const dx = Math.round((CANVAS_W - dw) / 2);
            const dy = GROUND_Y - dh;
            ctx.drawImage(src, sx, sy, sw, sh, dx, dy, dw, dh);
            texture.refresh();
        });
    }

    // ─── RAIL SHEET SLICER ───────────────────────────────────────

    /** The rail sheet is a 4x2 grid of run-cycle poses (top row = upright
     *  strides, bottom row = stretched gallops) with per-frame transparent
     *  padding. Slice it into named textures trimmed to the bird's bounding
     *  box and re-anchored bottom-center on a shared canvas so the feet stay
     *  on one ground line across the whole cycle (no frame-to-frame jitter).
     *  Derived poses (hiding / calling / surprised) are generated from the
     *  closest matching stride since no dedicated art exists for them. */
    sliceRailSheet() {
        if (!this.textures.exists('rail_sheet')) return;

        const FRAME_W = 1000;
        const FRAME_H = 1116;
        const CANVAS_W = 864;
        const CANVAS_H = 624;
        const src = this.textures.get('rail_sheet').source[0].image;

        const makeTex = (key, frameIndex, squashY = 1) => {
            const fx = (frameIndex % 4) * FRAME_W;
            const fy = Math.floor(frameIndex / 4) * FRAME_H;

            // Trim transparent padding via an alpha scan of this frame cell
            const scan = document.createElement('canvas');
            scan.width = FRAME_W;
            scan.height = FRAME_H;
            const sctx = scan.getContext('2d', { willReadFrequently: true });
            sctx.drawImage(src, fx, fy, FRAME_W, FRAME_H, 0, 0, FRAME_W, FRAME_H);
            const data = sctx.getImageData(0, 0, FRAME_W, FRAME_H).data;

            let minX = FRAME_W, minY = FRAME_H, maxX = -1, maxY = -1;
            for (let y = 0; y < FRAME_H; y++) {
                for (let x = 0; x < FRAME_W; x++) {
                    if (data[(y * FRAME_W + x) * 4 + 3] > 8) {
                        if (x < minX) minX = x;
                        if (x > maxX) maxX = x;
                        if (y < minY) minY = y;
                        if (y > maxY) maxY = y;
                    }
                }
            }
            if (maxX < 0) return;

            const cw = maxX - minX + 1;
            const ch = Math.round((maxY - minY + 1) * squashY);

            if (this.textures.exists(key)) this.textures.remove(key);
            const tex = this.textures.createCanvas(key, CANVAS_W, CANVAS_H);
            if (!tex) return;
            const ctx = tex.getContext();
            ctx.imageSmoothingEnabled = true;
            ctx.imageSmoothingQuality = 'high';
            // Bottom-center anchor: feet on the ground line, squash keeps them there
            const dx = Math.round((CANVAS_W - cw) / 2);
            ctx.drawImage(scan, minX, minY, cw, maxY - minY + 1, dx, CANVAS_H - ch, cw, ch);
            tex.refresh();
        };

        // Top row: upright strides → default run cycle
        for (let i = 0; i < 4; i++) makeTex(`rail_running_${i + 1}`, i);
        // Bottom row: stretched gallops → speed-boost sprint cycle
        for (let i = 0; i < 4; i++) makeTex(`rail_sprint_${i + 1}`, i + 4);
        // Derived poses
        makeTex('rail_hiding', 2, 0.72);   // crouched low in vegetation
        makeTex('rail_calling', 0);        // head-up alert stance
        makeTex('rail_surprised', 2);      // mid-stride alarm
    }

    // ─── PLANT SHEET SLICER ────────────────────────────────────

    /** Each `{key}_sprite_sheet.png` is a 4x2 grid of growth stages
     *  (sprout → mature). Cells have no gutters and mature plants bleed
     *  across cell borders, so each cell is cropped, reduced to its
     *  largest connected alpha mass (dropping neighbour-plant slivers),
     *  trimmed, and anchored bottom-centre on a per-plant shared canvas —
     *  growth then rises from the planting point with steady feet.
     *  Generates `{key}_1..{key}_8` plus a `{key}` mature alias
     *  (and the legacy `plant` alias for gumplant). */
    slicePlantSheets() {
        const PLANT_STAGE_BOUNDS = {
            gumplant: [
                { x: 172, y: 291, w: 141, h: 109 },
                { x: 517, y: 238, w: 203, h: 162 },
                { x: 876, y: 180, w: 262, h: 222 },
                { x: 1280, y: 110, w: 366, h: 292 },
                { x: 24, y: 513, w: 374, h: 311 },
                { x: 413, y: 503, w: 376, h: 326 },
                { x: 801, y: 469, w: 418, h: 362 },
                { x: 1240, y: 456, w: 522, h: 376 },
            ],
            cordgrass: [
                { x: 147, y: 233, w: 114, h: 149 },
                { x: 497, y: 159, w: 236, h: 224 },
                { x: 906, y: 78, w: 325, h: 305 },
                { x: 1346, y: 19, w: 376, h: 364 },
                { x: 30, y: 454, w: 368, h: 385 },
                { x: 434, y: 430, w: 401, h: 409 },
                { x: 838, y: 420, w: 445, h: 419 },
                { x: 1287, y: 420, w: 475, h: 423 },
            ],
            pickleweed: [
                { x: 166, y: 192, w: 121, h: 176 },
                { x: 551, y: 118, w: 187, h: 265 },
                { x: 886, y: 72, w: 330, h: 325 },
                { x: 1322, y: 17, w: 407, h: 392 },
                { x: 32, y: 482, w: 373, h: 348 },
                { x: 448, y: 476, w: 378, h: 358 },
                { x: 848, y: 473, w: 417, h: 375 },
                { x: 1289, y: 433, w: 468, h: 420 },
            ],
            saltgrass: [
                { x: 154, y: 229, w: 114, h: 154 },
                { x: 477, y: 198, w: 204, h: 186 },
                { x: 832, y: 88, w: 286, h: 296 },
                { x: 1259, y: 28, w: 370, h: 356 },
                { x: 44, y: 511, w: 338, h: 316 },
                { x: 395, y: 443, w: 398, h: 386 },
                { x: 800, y: 427, w: 427, h: 404 },
                { x: 1240, y: 420, w: 516, h: 415 },
            ],
            jaumea: [
                { x: 134, y: 202, w: 164, h: 151 },
                { x: 514, y: 123, w: 230, h: 240 },
                { x: 904, y: 79, w: 274, h: 287 },
                { x: 1361, y: 50, w: 332, h: 319 },
                { x: 25, y: 495, w: 344, h: 324 },
                { x: 400, y: 478, w: 407, h: 345 },
                { x: 813, y: 450, w: 412, h: 376 },
                { x: 1240, y: 436, w: 515, h: 404 },
            ],
        };

        const KEYS = ['gumplant', 'saltgrass', 'pickleweed', 'cordgrass', 'jaumea'];
        KEYS.forEach((key) => {
            const sheetKey = `${key}_sheet`;
            if (!this.textures.exists(sheetKey)) return;
            const src = this.textures.get(sheetKey).source[0].image;
            const stageBounds = PLANT_STAGE_BOUNDS[key];
            if (!stageBounds) return;

            let maxW = 1, maxH = 1;
            stageBounds.forEach((b) => {
                maxW = Math.max(maxW, b.w);
                maxH = Math.max(maxH, b.h);
            });

            const paint = (texKey, b) => {
                if (this.textures.exists(texKey)) this.textures.remove(texKey);
                const tex = this.textures.createCanvas(texKey, maxW, maxH);
                if (!tex) return;
                const ctx = tex.getContext();
                ctx.imageSmoothingEnabled = true;
                ctx.imageSmoothingQuality = 'high';
                const dx = Math.round((maxW - b.w) / 2);
                const dy = maxH - b.h;
                ctx.drawImage(src, b.x, b.y, b.w, b.h, dx, dy, b.w, b.h);
                tex.refresh();
            };

            for (let i = 0; i < stageBounds.length; i++) {
                paint(`${key}_${i + 1}`, stageBounds[i]);
            }
            const mature = stageBounds[stageBounds.length - 1];
            paint(key, mature);
            if (key === 'gumplant') paint('plant', mature);

            this.textures.remove(sheetKey);
        });
    }

    /** Crop (sx, sy, sw, sh) from src, keep only the largest connected
     *  alpha mass, and return its trimmed canvas + bbox (or null). */
    _trimLargestBlob(src, sx, sy, sw, sh) {        const cell = document.createElement('canvas');
        cell.width = sw;
        cell.height = sh;
        const cctx = cell.getContext('2d', { willReadFrequently: true });
        cctx.drawImage(src, sx, sy, sw, sh, 0, 0, sw, sh);
        const data = cctx.getImageData(0, 0, sw, sh).data;

        const mask = new Uint8Array(sw * sh);
        for (let i = 0; i < sw * sh; i++) {
            mask[i] = data[i * 4 + 3] > 8 ? 1 : 0;
        }

        // Union-find over right/down neighbours
        const parent = new Int32Array(sw * sh);
        for (let i = 0; i < sw * sh; i++) parent[i] = i;
        const find = (a) => {
            while (parent[a] !== a) {
                parent[a] = parent[parent[a]];
                a = parent[a];
            }
            return a;
        };
        for (let y = 0; y < sh; y++) {
            for (let x = 0; x < sw; x++) {
                const i = y * sw + x;
                if (!mask[i]) continue;
                if (x + 1 < sw && mask[i + 1]) {
                    const ra = find(i), rb = find(i + 1);
                    if (ra !== rb) parent[ra] = rb;
                }
                if (y + 1 < sh && mask[i + sw]) {
                    const ra = find(i), rb = find(i + sw);
                    if (ra !== rb) parent[ra] = rb;
                }
            }
        }

        // Largest component wins (neighbour-plant slivers are severed
        // by the crop and stay small + disconnected)
        const counts = new Map();
        let best = -1, bestCount = 0;
        for (let i = 0; i < sw * sh; i++) {
            if (!mask[i]) continue;
            const r = find(i);
            const c = (counts.get(r) || 0) + 1;
            counts.set(r, c);
            if (c > bestCount) {
                bestCount = c;
                best = r;
            }
        }
        if (best < 0) return null;

        let minX = sw, minY = sh, maxX = -1, maxY = -1;
        for (let y = 0; y < sh; y++) {
            for (let x = 0; x < sw; x++) {
                const i = y * sw + x;
                if (mask[i] && find(i) === best) {
                    if (x < minX) minX = x;
                    if (x > maxX) maxX = x;
                    if (y < minY) minY = y;
                    if (y > maxY) maxY = y;
                } else {
                    data[i * 4 + 3] = 0;
                }
            }
        }
        cctx.putImageData(new ImageData(data, sw, sh), 0, 0);
        return {
            canvas: cell,
            x: minX, y: minY,
            w: maxX - minX + 1, h: maxY - minY + 1,
        };
    }

    // ─── HARRIER SHEET SLICER ────────────────────────────────

    /** The harrier sheet is 1774x887: a top row of 6 glide poses and a
     *  bottom row of 4 dive/catch poses (with prey). Frames bleed across
     *  borders, so each is reduced to its largest connected alpha mass,
     *  trimmed, and CENTRE-anchored on a shared canvas (it flies — no
     *  ground line). Generates `harrier_glide_1..6`, `harrier_dive`
     *  (level-wing glide pose) and `harrier_kill` (carrying prey). */
    sliceHarrier() {
        const RAW = 'harrier_sheet_raw';
        if (!this.textures.exists(RAW)) return;
        const src = this.textures.get(RAW).source[0].image;

        const HARRIER_FRAME_BOUNDS = {
            harrier_glide_1: { x: 10, y: 92, w: 277, h: 263 },
            harrier_glide_2: { x: 310, y: 168, w: 311, h: 191 },
            harrier_glide_3: { x: 639, y: 140, w: 267, h: 216 },
            harrier_glide_4: { x: 927, y: 241, w: 287, h: 118 },
            harrier_glide_5: { x: 1239, y: 124, w: 247, h: 237 },
            harrier_glide_6: { x: 1503, y: 88, w: 266, h: 271 },
            harrier_dive: { x: 501, y: 450, w: 288, h: 270 },
            harrier_catch: { x: 948, y: 500, w: 309, h: 345 },
            harrier_kill: { x: 1369, y: 406, w: 329, h: 413 },
        };

        const entries = Object.entries(HARRIER_FRAME_BOUNDS);
        const stages = entries.map(([key, b]) => ({
            key,
            stage: this._trimLargestBlob(src, b.x, b.y, b.w, b.h),
        }));

        let maxW = 1, maxH = 1;
        stages.forEach(({ stage }) => {
            if (stage) {
                maxW = Math.max(maxW, stage.w);
                maxH = Math.max(maxH, stage.h);
            }
        });

        stages.forEach(({ key, stage }) => {
            if (this.textures.exists(key)) this.textures.remove(key);
            const tex = this.textures.createCanvas(key, maxW, maxH);
            if (!tex) return;
            const ctx = tex.getContext();
            ctx.imageSmoothingEnabled = true;
            ctx.imageSmoothingQuality = 'high';
            if (stage) {
                ctx.drawImage(
                    stage.canvas, stage.x, stage.y, stage.w, stage.h,
                    Math.round((maxW - stage.w) / 2), Math.round((maxH - stage.h) / 2),
                    stage.w, stage.h
                );
            }
            tex.refresh();
        });

        this.textures.remove(RAW);
    }

    // ─── HARRIER TEXTURE GENERATORS (Northern Harrier / Marsh Hawk) ───

}
