import * as Phaser from 'phaser';

export class BootScene extends Phaser.Scene {
    constructor() {
        super({ key: 'BootScene' });
    }

    preload() {
        // Get loading bar element
        const loadingBar = document.getElementById('loading-bar');

        // Update loading bar as assets load
        this.load.on('progress', (value) => {
            if (loadingBar) {
                loadingBar.style.width = `${value * 100}%`;
            }
        });

        this.load.on('complete', () => {
            // Hide loading screen with fade
            const loadingScreen = document.getElementById('loading-screen');
            if (loadingScreen) {
                loadingScreen.classList.add('hidden');
                setTimeout(() => {
                    loadingScreen.style.display = 'none';
                }, 500);
            }
        });

        // Load Ridgways Rail sprite sheet (4x2 grid, 4000x2233 -> 1000x1116 per frame)
        this.load.spritesheet('rail_sheet', 'assets/sprites/rail_sprite_sheet.png', { frameWidth: 1000, frameHeight: 1116 });

        // Load Fox sprite sheet
        this.load.spritesheet('fox_sheet', 'assets/sprites/gray_fox_sprite_sheet.png', { frameWidth: 688, frameHeight: 768 });

        // Load Harrier sprite sheet (4x4 grid, 4000x2233 -> 1000x558 per frame)
        this.load.spritesheet('harrier_sheet', 'assets/sprites/northern_harrier_sprite.png', { frameWidth: 1000, frameHeight: 558 });

        // Load Cat sprite sheet (7x2 grid, 3500x1014 -> 500x507 per frame)
        this.load.spritesheet('cat_sheet', 'assets/sprites/cat_with_padding.png', {
            frameWidth: 500,
            frameHeight: 507
        });

        // Load plant growth sheets (4x2 grid of stages, sprout → mature)
        ['gumplant', 'saltgrass', 'pickleweed', 'cordgrass', 'jaumea'].forEach((key) => {
            this.load.image(`${key}_sheet`, `assets/sprites/${key}_sprite_sheet.png`);
        });
        // Legacy 'plant' key aliases the mature gumplant (set up in slicePlantSheets)

        // Load Intro Video
        this.load.video('intro_video', 'assets/title_movie.mp4');

        // Create placeholder graphics for other assets
        this.createPlaceholderAssets();
    }

    createPlaceholderAssets() {

        // ── PLANT GROWTH STAGES (sliced from sprite sheets in create()) ──
        // Saltgrass / pickleweed / cordgrass / jaumea / gumplant textures
        // (`{key}_1..{key}_8` + `{key}` aliases) are generated by
        // slicePlantSheets() once the sheet images have loaded.

        // Water tile (64x64) – deep tidal water with depth banding & seamless waves
        const waterGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        // Deep base
        waterGraphics.fillStyle(0x0a3149);
        waterGraphics.fillRect(0, 0, 64, 64);
        // Depth banding
        waterGraphics.fillStyle(0x0d425f, 0.6);
        waterGraphics.fillRect(0, 22, 64, 42);
        // Wave crests – integer sine cycles so the tile repeats seamlessly
        for (let row = 0; row < 4; row++) {
            const yBase = 6 + row * 16;
            waterGraphics.lineStyle(2, 0x2f86ad, 0.32);
            waterGraphics.beginPath();
            waterGraphics.moveTo(0, yBase + Math.sin(row * 1.7) * 2.2);
            for (let x = 0; x <= 64; x += 4) {
                const t = (x / 64) * Math.PI * 2;
                waterGraphics.lineTo(x, yBase + Math.sin(t * 2 + row * 1.7) * 2.2);
            }
            waterGraphics.strokePath();
        }
        // Secondary ripple lines
        waterGraphics.lineStyle(1, 0x7fd4e8, 0.22);
        for (let row = 0; row < 3; row++) {
            const yBase = 13 + row * 21;
            waterGraphics.beginPath();
            waterGraphics.moveTo(0, yBase + Math.cos(row * 2.3) * 1.6);
            for (let x = 0; x <= 64; x += 4) {
                const t = (x / 64) * Math.PI * 2;
                waterGraphics.lineTo(x, yBase + Math.cos(t * 3 + row * 2.3) * 1.6);
            }
            waterGraphics.strokePath();
        }
        // Subtle foam dots
        waterGraphics.fillStyle(0xffffff, 0.10);
        [
            [8, 6], [30, 18], [52, 10], [14, 42], [44, 50], [58, 34], [22, 58],
        ].forEach(([px, py]) => waterGraphics.fillCircle(px, py, 1.5));
        waterGraphics.generateTexture('water', 64, 64);
        waterGraphics.destroy();

        // Vertical depth shade for the water body (real canvas gradient)
        if (this.textures.exists('water_shade')) this.textures.remove('water_shade');
        const shadeTex = this.textures.createCanvas('water_shade', 4, 64);
        const shadeCtx = shadeTex.getContext();
        const shadeGrad = shadeCtx.createLinearGradient(0, 0, 0, 64);
        shadeGrad.addColorStop(0, 'rgba(5,26,40,0)');
        shadeGrad.addColorStop(0.6, 'rgba(5,26,40,0.18)');
        shadeGrad.addColorStop(1, 'rgba(5,26,40,0.5)');
        shadeCtx.fillStyle = shadeGrad;
        shadeCtx.fillRect(0, 0, 4, 64);
        shadeTex.refresh();

        // Soft contact shadow (radial gradient squashed into an ellipse)
        if (this.textures.exists('shadow')) this.textures.remove('shadow');
        const shadowTex = this.textures.createCanvas('shadow', 128, 40);
        const shadowCtx = shadowTex.getContext();
        shadowCtx.translate(64, 20);
        shadowCtx.scale(1, 0.32);
        shadowCtx.translate(-64, -20);
        const shadowGrad = shadowCtx.createRadialGradient(64, 20, 2, 64, 20, 60);
        shadowGrad.addColorStop(0, 'rgba(0,0,0,0.42)');
        shadowGrad.addColorStop(0.7, 'rgba(0,0,0,0.20)');
        shadowGrad.addColorStop(1, 'rgba(0,0,0,0)');
        shadowCtx.fillStyle = shadowGrad;
        shadowCtx.fillRect(-10, -60, 148, 160);
        shadowTex.refresh();

        // Water-edge / shoreline overlay (16x64) for foam & wet-sand at the tide front
        const edgeGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        // Wet sand strip
        edgeGraphics.fillGradientStyle(0x3a6e9f, 0x3a6e9f, 0x5d4e37, 0x5d4e37);
        edgeGraphics.fillRect(0, 0, 16, 64);
        // Foam line
        edgeGraphics.fillStyle(0xffffff, 0.55);
        edgeGraphics.fillRect(0, 0, 4, 64);
        edgeGraphics.fillStyle(0xffffff, 0.3);
        edgeGraphics.fillRect(4, 0, 3, 64);
        // Scattered foam blobs
        edgeGraphics.fillStyle(0xffffff, 0.25);
        [6, 18, 30, 44, 56].forEach(py => {
            edgeGraphics.fillCircle(3, py, 2);
            edgeGraphics.fillCircle(7, py + 8, 1.5);
        });
        edgeGraphics.generateTexture('water_edge', 16, 64);
        edgeGraphics.destroy();

        // Mud/transition zone tile (64x64)
        const mudGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        mudGraphics.fillStyle(0x5d4e37);
        mudGraphics.fillRect(0, 0, 64, 64);
        // Texture details
        mudGraphics.fillStyle(0x4a3f2d, 0.5);
        mudGraphics.fillCircle(10, 15, 5);
        mudGraphics.fillCircle(45, 30, 7);
        mudGraphics.fillCircle(25, 50, 4);
        mudGraphics.fillCircle(55, 10, 3);
        mudGraphics.generateTexture('mud', 64, 64);
        mudGraphics.destroy();

        // Upland/grass tile (64x64)
        const grassGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        grassGraphics.fillStyle(0x4a7c23);
        grassGraphics.fillRect(0, 0, 64, 64);
        // Grass blades
        grassGraphics.fillStyle(0x5a8c33);
        for (let i = 0; i < 20; i++) {
            const x = Math.random() * 64;
            const y = Math.random() * 64;
            grassGraphics.fillTriangle(x, y + 8, x + 3, y, x + 6, y + 8);
        }
        grassGraphics.generateTexture('grass', 64, 64);
        grassGraphics.destroy();

        // Seed particle (16x16)
        const seedGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        seedGraphics.fillStyle(0xf39c12);
        seedGraphics.fillCircle(8, 8, 4);
        seedGraphics.fillStyle(0xffffff, 0.5);
        seedGraphics.lineStyle(1, 0xffffff, 0.7);
        seedGraphics.beginPath();
        seedGraphics.moveTo(8, 4);
        seedGraphics.lineTo(8, 0);
        seedGraphics.lineTo(12, 2);
        seedGraphics.stroke();
        seedGraphics.generateTexture('seed', 16, 16);
        seedGraphics.destroy();

        // Heart particle (16x16)
        const heartGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        heartGraphics.fillStyle(0xff6b9d);
        heartGraphics.fillCircle(5, 6, 4);
        heartGraphics.fillCircle(11, 6, 4);
        heartGraphics.fillTriangle(1, 8, 8, 15, 15, 8);
        heartGraphics.generateTexture('heart', 16, 16);
        heartGraphics.destroy();

        // Dirt particle (8x8)
        const dirtGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        dirtGraphics.fillStyle(0x8b7355);
        dirtGraphics.fillCircle(4, 4, 3);
        dirtGraphics.generateTexture('dirt', 8, 8);
        dirtGraphics.destroy();

        // Button texture (200x60)
        const buttonGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        buttonGraphics.fillStyle(0x27ae60);
        buttonGraphics.fillRoundedRect(0, 0, 200, 60, 12);
        buttonGraphics.lineStyle(3, 0x2ecc71);
        buttonGraphics.strokeRoundedRect(0, 0, 200, 60, 12);
        buttonGraphics.generateTexture('button', 200, 60);
        buttonGraphics.destroy();

        // Button hover texture
        const buttonHoverGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        buttonHoverGraphics.fillStyle(0x2ecc71);
        buttonHoverGraphics.fillRoundedRect(0, 0, 200, 60, 12);
        buttonHoverGraphics.lineStyle(3, 0x58d68d);
        buttonHoverGraphics.strokeRoundedRect(0, 0, 200, 60, 12);
        buttonHoverGraphics.generateTexture('button_hover', 200, 60);
        buttonHoverGraphics.destroy();

        // ── HUD panel texture (reused for all panels) ──
        // Compact top-bar panel 220×52
        const hPnl = this.make.graphics({ x: 0, y: 0, add: false });
        hPnl.fillStyle(0x0c1a0c, 0.82);
        hPnl.fillRoundedRect(0, 0, 220, 52, 10);
        hPnl.lineStyle(1, 0x3ddc84, 0.35);
        hPnl.strokeRoundedRect(0, 0, 220, 52, 10);
        hPnl.generateTexture('hud_panel', 220, 52);
        hPnl.destroy();

        // Wide panel for seed bar 260×52
        const hPnlW = this.make.graphics({ x: 0, y: 0, add: false });
        hPnlW.fillStyle(0x0c1a0c, 0.82);
        hPnlW.fillRoundedRect(0, 0, 260, 52, 10);
        hPnlW.lineStyle(1, 0xf39c12, 0.35);
        hPnlW.strokeRoundedRect(0, 0, 260, 52, 10);
        hPnlW.generateTexture('hud_panel_wide', 260, 52);
        hPnlW.destroy();

        // Bottom stats bar full-width 480×40
        const hPnlB = this.make.graphics({ x: 0, y: 0, add: false });
        hPnlB.fillStyle(0x0c1a0c, 0.72);
        hPnlB.fillRoundedRect(0, 0, 480, 36, 8);
        hPnlB.lineStyle(1, 0xffffff, 0.15);
        hPnlB.strokeRoundedRect(0, 0, 480, 36, 8);
        hPnlB.generateTexture('hud_panel_bottom', 480, 36);
        hPnlB.destroy();

        // Legacy textures kept for menu / game-over scenes
        const seedBankGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        seedBankGraphics.fillStyle(0x000000, 0.4);
        seedBankGraphics.fillRoundedRect(0, 0, 280, 80, 16);
        seedBankGraphics.lineStyle(2, 0xffffff, 0.2);
        seedBankGraphics.strokeRoundedRect(0, 0, 280, 80, 16);
        seedBankGraphics.generateTexture('seedbank_bg', 280, 80);
        seedBankGraphics.destroy();

        const scorePanelGraphics = this.make.graphics({ x: 0, y: 0, add: false });
        scorePanelGraphics.fillStyle(0x000000, 0.4);
        scorePanelGraphics.fillRoundedRect(0, 0, 200, 120, 16);
        scorePanelGraphics.lineStyle(2, 0xffffff, 0.2);
        scorePanelGraphics.strokeRoundedRect(0, 0, 200, 120, 16);
        scorePanelGraphics.generateTexture('score_panel', 200, 120);
        scorePanelGraphics.destroy();

        // ── HUD ICON TEXTURES (replacing emojis) ────────────
        this.createIconTextures();

        // ── Apply NEAREST filtering to all generated sprite textures ──
        // This keeps pixel art crisp while text stays smooth (LINEAR default).
        this.applyNearestFilter();
    }

    /** Set NEAREST filtering on pixel-art sprite textures so they stay
     *  crisp at any zoom. Plant growth stages are photographic art and
     *  intentionally keep LINEAR filtering; text keeps LINEAR too. */
    applyNearestFilter() {
        const spriteKeys = [
            'fox', 'cat',
            'cat_walking_1', 'cat_walking_2', 'cat_walking_3', 'cat_walking_4',
            'cat_pouncing', 'cat_with_kill',
            'water', 'water_edge', 'mud', 'grass',
            'seed', 'heart', 'dirt',
            'button', 'button_hover',
            'seedbank_bg', 'score_panel',
            'hud_panel', 'hud_panel_wide', 'hud_panel_bottom',
            // Rail sheet slices
            'rail_running_1', 'rail_running_2', 'rail_running_3', 'rail_running_4',
            'rail_sprint_1', 'rail_sprint_2', 'rail_sprint_3', 'rail_sprint_4',
            'rail_hiding', 'rail_calling', 'rail_surprised',
            // Icon textures (emoji replacements)
            'icon_trophy', 'icon_heart_green', 'icon_heart_broken',
            'icon_leaf', 'icon_flame', 'icon_wave',
            'icon_paw', 'icon_bolt', 'icon_target', 'icon_star',
            'fox_sheet',
            'cat_sheet',
        ];
        spriteKeys.forEach(key => {
            const tex = this.textures.get(key);
            if (tex && tex.source && tex.source[0]) {
                tex.setFilter(Phaser.Textures.FilterMode.NEAREST);
            }
        });
    }

    create() {
        // Split the rail sheet into named textures (Rail.js references these keys)
        this.sliceRailSheet();

        // Split plant growth sheets into staged textures (Plant.js uses these)
        this.slicePlantSheets();

        // Re-apply NEAREST now that the sliced rail textures exist
        // (plant stage textures intentionally keep LINEAR filtering)
        this.applyNearestFilter();

        // Transition to menu scene
        this.scene.start('MenuScene');
    }

    // ─── RAIL SHEET SLICER ───────────────────────────────────────

    /** The rail sheet is a 4x2 grid of run-cycle poses (top row = upright
     *  strides, bottom row = stretched gallops) with per-frame transparent
     *  padding. Slice it into named textures trimmed to the bird's bounding
     *  box and re-anchored bottom-center on a shared canvas so the feet stay
     *  on one ground line across the whole cycle (no frame-to-frame jitter).
     *  Derived poses (hiding / calling / surprised) are generated from the
     *  closest matching stride since no dedicated art exists for them. */
    sliceRailSheet() {
        if (!this.textures.exists('rail_sheet')) return;

        const FRAME_W = 1000;
        const FRAME_H = 1116;
        const CANVAS_W = 864;
        const CANVAS_H = 624;
        const src = this.textures.get('rail_sheet').source[0].image;

        const makeTex = (key, frameIndex, squashY = 1) => {
            const fx = (frameIndex % 4) * FRAME_W;
            const fy = Math.floor(frameIndex / 4) * FRAME_H;

            // Trim transparent padding via an alpha scan of this frame cell
            const scan = document.createElement('canvas');
            scan.width = FRAME_W;
            scan.height = FRAME_H;
            const sctx = scan.getContext('2d', { willReadFrequently: true });
            sctx.drawImage(src, fx, fy, FRAME_W, FRAME_H, 0, 0, FRAME_W, FRAME_H);
            const data = sctx.getImageData(0, 0, FRAME_W, FRAME_H).data;

            let minX = FRAME_W, minY = FRAME_H, maxX = -1, maxY = -1;
            for (let y = 0; y < FRAME_H; y++) {
                for (let x = 0; x < FRAME_W; x++) {
                    if (data[(y * FRAME_W + x) * 4 + 3] > 8) {
                        if (x < minX) minX = x;
                        if (x > maxX) maxX = x;
                        if (y < minY) minY = y;
                        if (y > maxY) maxY = y;
                    }
                }
            }
            if (maxX < 0) return;

            const cw = maxX - minX + 1;
            const ch = Math.round((maxY - minY + 1) * squashY);

            if (this.textures.exists(key)) this.textures.remove(key);
            const tex = this.textures.createCanvas(key, CANVAS_W, CANVAS_H);
            if (!tex) return;
            const ctx = tex.getContext();
            ctx.imageSmoothingEnabled = true;
            ctx.imageSmoothingQuality = 'high';
            // Bottom-center anchor: feet on the ground line, squash keeps them there
            const dx = Math.round((CANVAS_W - cw) / 2);
            ctx.drawImage(scan, minX, minY, cw, maxY - minY + 1, dx, CANVAS_H - ch, cw, ch);
            tex.refresh();
        };

        // Top row: upright strides → default run cycle
        for (let i = 0; i < 4; i++) makeTex(`rail_running_${i + 1}`, i);
        // Bottom row: stretched gallops → speed-boost sprint cycle
        for (let i = 0; i < 4; i++) makeTex(`rail_sprint_${i + 1}`, i + 4);
        // Derived poses
        makeTex('rail_hiding', 2, 0.72);   // crouched low in vegetation
        makeTex('rail_calling', 0);        // head-up alert stance
        makeTex('rail_surprised', 2);      // mid-stride alarm
    }

    // ─── PLANT SHEET SLICER ────────────────────────────────────

    /** Each `{key}_sprite_sheet.png` is a 4x2 grid of growth stages
     *  (sprout → mature). Cells have no gutters and mature plants bleed
     *  across cell borders, so each cell is cropped, reduced to its
     *  largest connected alpha mass (dropping neighbour-plant slivers),
     *  trimmed, and anchored bottom-centre on a per-plant shared canvas —
     *  growth then rises from the planting point with steady feet.
     *  Generates `{key}_1..{key}_8` plus a `{key}` mature alias
     *  (and the legacy `plant` alias for gumplant). */
    slicePlantSheets() {
        const KEYS = ['gumplant', 'saltgrass', 'pickleweed', 'cordgrass', 'jaumea'];
        const COLS = 4, ROWS = 2, INSET = 6;
        KEYS.forEach((key) => {
            const sheetKey = `${key}_sheet`;
            if (!this.textures.exists(sheetKey)) return;
            const src = this.textures.get(sheetKey).source[0].image;
            const cw = src.width / COLS;
            const ch = src.height / ROWS;

            const stages = [];
            let maxW = 1, maxH = 1;
            for (let i = 0; i < COLS * ROWS; i++) {
                const cx = i % COLS, cy = Math.floor(i / COLS);
                const sx = Math.round(cx * cw + INSET);
                const sy = Math.round(cy * ch + INSET);
                const sw = Math.round(cw - INSET * 2);
                const sh = Math.round(ch - INSET * 2);
                const trimmed = this._trimLargestBlob(src, sx, sy, sw, sh);
                if (trimmed) {
                    maxW = Math.max(maxW, trimmed.w);
                    maxH = Math.max(maxH, trimmed.h);
                }
                stages.push(trimmed);
            }

            const paint = (texKey, stage) => {
                if (this.textures.exists(texKey)) this.textures.remove(texKey);
                const tex = this.textures.createCanvas(texKey, maxW, maxH);
                if (!tex) return;
                const ctx = tex.getContext();
                ctx.imageSmoothingEnabled = true;
                ctx.imageSmoothingQuality = 'high';
                if (stage) {
                    ctx.drawImage(
                        stage.canvas, stage.x, stage.y, stage.w, stage.h,
                        Math.round((maxW - stage.w) / 2), maxH - stage.h,
                        stage.w, stage.h
                    );
                }
                tex.refresh();
            };

            for (let i = 0; i < stages.length; i++) {
                paint(`${key}_${i + 1}`, stages[i]);
            }
            // Mature-stage aliases keep existing references working
            paint(key, stages[stages.length - 1]);
            if (key === 'gumplant') paint('plant', stages[stages.length - 1]);

            // Free the sheet — stages now hold their own pixels
            this.textures.remove(sheetKey);
        });
    }

    /** Crop (sx, sy, sw, sh) from src, keep only the largest connected
     *  alpha mass, and return its trimmed canvas + bbox (or null). */
    _trimLargestBlob(src, sx, sy, sw, sh) {
        const cell = document.createElement('canvas');
        cell.width = sw;
        cell.height = sh;
        const cctx = cell.getContext('2d', { willReadFrequently: true });
        cctx.drawImage(src, sx, sy, sw, sh, 0, 0, sw, sh);
        const data = cctx.getImageData(0, 0, sw, sh).data;

        const mask = new Uint8Array(sw * sh);
        for (let i = 0; i < sw * sh; i++) {
            mask[i] = data[i * 4 + 3] > 8 ? 1 : 0;
        }

        // Union-find over right/down neighbours
        const parent = new Int32Array(sw * sh);
        for (let i = 0; i < sw * sh; i++) parent[i] = i;
        const find = (a) => {
            while (parent[a] !== a) {
                parent[a] = parent[parent[a]];
                a = parent[a];
            }
            return a;
        };
        for (let y = 0; y < sh; y++) {
            for (let x = 0; x < sw; x++) {
                const i = y * sw + x;
                if (!mask[i]) continue;
                if (x + 1 < sw && mask[i + 1]) {
                    const ra = find(i), rb = find(i + 1);
                    if (ra !== rb) parent[ra] = rb;
                }
                if (y + 1 < sh && mask[i + sw]) {
                    const ra = find(i), rb = find(i + sw);
                    if (ra !== rb) parent[ra] = rb;
                }
            }
        }

        // Largest component wins (neighbour-plant slivers are severed
        // by the crop and stay small + disconnected)
        const counts = new Map();
        let best = -1, bestCount = 0;
        for (let i = 0; i < sw * sh; i++) {
            if (!mask[i]) continue;
            const r = find(i);
            const c = (counts.get(r) || 0) + 1;
            counts.set(r, c);
            if (c > bestCount) {
                bestCount = c;
                best = r;
            }
        }
        if (best < 0) return null;

        let minX = sw, minY = sh, maxX = -1, maxY = -1;
        for (let y = 0; y < sh; y++) {
            for (let x = 0; x < sw; x++) {
                const i = y * sw + x;
                if (mask[i] && find(i) === best) {
                    if (x < minX) minX = x;
                    if (x > maxX) maxX = x;
                    if (y < minY) minY = y;
                    if (y > maxY) maxY = y;
                } else {
                    data[i * 4 + 3] = 0;
                }
            }
        }
        cctx.putImageData(new ImageData(data, sw, sh), 0, 0);
        return {
            canvas: cell,
            x: minX, y: minY,
            w: maxX - minX + 1, h: maxY - minY + 1,
        };
    }

    // ─── HARRIER TEXTURE GENERATORS (Northern Harrier / Marsh Hawk) ───

    // ─── ICON TEXTURES (emoji replacements) ──────────────────

    createIconTextures() {
        const S = 20; // icon size

        // Trophy (replaces 🏆)
        this._makeIcon('icon_trophy', S, (g) => {
            // Cup
            g.fillStyle(0xf1c40f);
            g.fillRoundedRect(5, 3, 10, 8, 2);
            // Handles
            g.lineStyle(2, 0xf1c40f);
            g.beginPath();
            g.arc(4, 7, 3, Math.PI * 0.5, Math.PI * 1.5, false);
            g.stroke();
            g.beginPath();
            g.arc(16, 7, 3, -Math.PI * 0.5, Math.PI * 0.5, false);
            g.stroke();
            // Stem
            g.fillStyle(0xd4ac0d);
            g.fillRect(8, 11, 4, 3);
            // Base
            g.fillStyle(0xf1c40f);
            g.fillRoundedRect(6, 14, 8, 3, 1);
        });

        // Green heart / check-heart (replaces 💚)
        this._makeIcon('icon_heart_green', S, (g) => {
            g.fillStyle(0x27ae60);
            g.fillCircle(7, 7, 4);
            g.fillCircle(13, 7, 4);
            g.fillTriangle(3, 9, 10, 17, 17, 9);
        });

        // Broken heart (replaces 💔)
        this._makeIcon('icon_heart_broken', S, (g) => {
            g.fillStyle(0xe74c3c);
            g.fillCircle(7, 7, 4);
            g.fillCircle(13, 7, 4);
            g.fillTriangle(3, 9, 10, 17, 17, 9);
            // Crack line
            g.lineStyle(1.5, 0x1a1a1a, 0.8);
            g.beginPath();
            g.moveTo(10, 5);
            g.lineTo(8, 9);
            g.lineTo(12, 11);
            g.lineTo(10, 16);
            g.stroke();
        });

        // Leaf (replaces 🌿)
        this._makeIcon('icon_leaf', S, (g) => {
            // Leaf shape
            g.fillStyle(0x27ae60);
            g.beginPath();
            g.moveTo(10, 2);
            g.lineTo(17, 8);
            g.lineTo(14, 14);
            g.lineTo(10, 16);
            g.lineTo(6, 14);
            g.lineTo(3, 8);
            g.closePath();
            g.fill();
            // Vein
            g.lineStyle(1, 0x1a5c1a, 0.6);
            g.beginPath();
            g.moveTo(10, 3);
            g.lineTo(10, 15);
            g.stroke();
            g.beginPath();
            g.moveTo(10, 7);
            g.lineTo(7, 10);
            g.stroke();
            g.beginPath();
            g.moveTo(10, 9);
            g.lineTo(13, 12);
            g.stroke();
        });

        // Flame (replaces 🔥)
        this._makeIcon('icon_flame', S, (g) => {
            g.fillStyle(0xe67e22);
            g.beginPath();
            g.moveTo(10, 2);
            g.lineTo(14, 8);
            g.lineTo(16, 14);
            g.lineTo(13, 18);
            g.lineTo(7, 18);
            g.lineTo(4, 14);
            g.lineTo(6, 8);
            g.closePath();
            g.fill();
            // Inner flame
            g.fillStyle(0xf39c12);
            g.beginPath();
            g.moveTo(10, 6);
            g.lineTo(13, 11);
            g.lineTo(12, 16);
            g.lineTo(8, 16);
            g.lineTo(7, 11);
            g.closePath();
            g.fill();
            // Core
            g.fillStyle(0xf1c40f);
            g.fillEllipse(10, 14, 4, 5);
        });

        // Wave (replaces 🌊)
        this._makeIcon('icon_wave', S, (g) => {
            g.lineStyle(2.5, 0x3498db);
            g.beginPath();
            g.moveTo(1, 10);
            for (let x = 0; x <= S; x += 1) {
                g.lineTo(x, 10 + Math.sin(x * 0.6) * 3);
            }
            g.stroke();
            g.lineStyle(2, 0x2980b9, 0.6);
            g.beginPath();
            g.moveTo(1, 15);
            for (let x = 0; x <= S; x += 1) {
                g.lineTo(x, 15 + Math.sin((x + 4) * 0.6) * 2);
            }
            g.stroke();
        });

        // Paw print (replaces 🦊 as predator icon)
        this._makeIcon('icon_paw', S, (g) => {
            g.fillStyle(0xd4ac0d);
            // Pad
            g.fillEllipse(10, 13, 8, 6);
            // Toes
            g.fillCircle(5, 7, 2.5);
            g.fillCircle(9, 5, 2.5);
            g.fillCircle(13, 5.5, 2.5);
            g.fillCircle(16, 8, 2.5);
        });

        // Lightning bolt (replaces ⚡)
        this._makeIcon('icon_bolt', S, (g) => {
            g.fillStyle(0xf1c40f);
            g.beginPath();
            g.moveTo(12, 1);
            g.lineTo(5, 10);
            g.lineTo(9, 10);
            g.lineTo(7, 19);
            g.lineTo(15, 9);
            g.lineTo(11, 9);
            g.closePath();
            g.fill();
        });

        // Target / crosshair (replaces 🎯)
        this._makeIcon('icon_target', S, (g) => {
            g.lineStyle(2, 0xe74c3c);
            g.strokeCircle(10, 10, 7);
            g.strokeCircle(10, 10, 3);
            g.fillStyle(0xe74c3c);
            g.fillCircle(10, 10, 1.5);
        });

        // Star (generic reward icon)
        this._makeIcon('icon_star', S, (g) => {
            g.fillStyle(0xf1c40f);
            const cx = 10, cy = 10, spikes = 5, outer = 8, inner = 4;
            g.beginPath();
            for (let i = 0; i < spikes * 2; i++) {
                const r = i % 2 === 0 ? outer : inner;
                const angle = (i * Math.PI / spikes) - Math.PI / 2;
                const px = cx + Math.cos(angle) * r;
                const py = cy + Math.sin(angle) * r;
                if (i === 0) g.moveTo(px, py);
                else g.lineTo(px, py);
            }
            g.closePath();
            g.fill();
        });
    }

    /** Helper to create a small icon texture */
    _makeIcon(key, size, drawFn) {
        const g = this.make.graphics({ x: 0, y: 0, add: false });
        drawFn(g);
        g.generateTexture(key, size, size);
        g.destroy();
    }
}
